// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void Vreme_rada_m1(lv_event_t * e)
{
	// Your code here
}

void Vreme_rada_m2(lv_event_t * e)
{
	// Your code here
}

void Vreme_pauze(lv_event_t * e)
{
	// Your code here
}

void Zeljena_temp_radionice(lv_event_t * e)
{
	// Your code here
}

void Max_temp_kotla(lv_event_t * e)
{
	// Your code here
}
