// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include <stdlib.h>



// Global variables to store the values
int vreme_rada_motor1 = 0;      // Time for motor 1 (in seconds or minutes)
int vreme_rada_motor2 = 0;      // Time for motor 2 (in seconds or minutes)
int vreme_pauze = 0;            // Pause time (in seconds or minutes)
int zeljena_temp_radionice = 0; // Desired workshop temperature
int max_temp_kotla = 0;         // Maximum boiler temperature

void Vreme_rada_m1(lv_event_t * e)
{
	// Get the text from TextArea3 (from rezimi_rada screen)
	const char* text = lv_textarea_get_text(ui_TextArea3);
	
	// Convert text to integer and store in variable
	vreme_rada_motor1 = atoi(text);
	
	// Update the label (ui_Label18) to show the value
	lv_label_set_text(ui_Label18, text);
	

	
	// Optional: Clear the text area after submission
	 lv_textarea_set_text(ui_TextArea3, "");
}

void Vreme_rada_m2(lv_event_t * e)
{
	// Get the text from TextArea3 (from rezimi_rada screen)
	const char* text = lv_textarea_get_text(ui_TextArea3);
	
	// Convert text to integer and store in variable
	vreme_rada_motor2 = atoi(text);
	
	// Update the label (ui_Label19) to show the value
	lv_label_set_text(ui_Label19, text);
	
	
	
	// Optional: Clear the text area after submission
	 lv_textarea_set_text(ui_TextArea3, "");
}

void Vreme_pauze(lv_event_t * e)
{
	// Get the text from TextArea3 (from rezimi_rada screen)
	const char* text = lv_textarea_get_text(ui_TextArea3);
	
	// Convert text to integer and store in variable
	vreme_pauze = atoi(text);
	
	// Update the label (ui_Label24) to show the value
	lv_label_set_text(ui_Label24, text);

	
	// Optional: Clear the text area after submission
	 lv_textarea_set_text(ui_TextArea3, "");
}

void Zeljena_temp_radionice(lv_event_t * e)
{
	// Get the text from TextArea1 (from zadavanje_temperatura screen)
	const char* text = lv_textarea_get_text(ui_TextArea1);
	
	// Convert text to integer and store in variable
	zeljena_temp_radionice = atoi(text);
	
	// Update the label (ui_Label26) to show the value
	lv_label_set_text(ui_Label7, text);
	
	
	// Optional: Clear the text area after submission
	 lv_textarea_set_text(ui_TextArea1, "");
}

void Maks_temp_kotla(lv_event_t * e)
{
	// Get the text from TextArea1 (from zadavanje_temperatura screen)
	const char* text = lv_textarea_get_text(ui_TextArea1);
	
	// Convert text to integer and store in variable
	max_temp_kotla = atoi(text);
	
	// Update the label (ui_Label27) to show the value
	lv_label_set_text(ui_Label8, text);
	
	// Optional: Print to serial for debugging

	
	// Optional: Clear the text area after submission
	 lv_textarea_set_text(ui_TextArea1, "");
}
	
