// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void Vreme_rada_m1(lv_event_t * e);
void Vreme_rada_m2(lv_event_t * e);
void Vreme_pauze(lv_event_t * e);
void Zeljena_temp_radionice(lv_event_t * e);
void Maks_temp_kotla(lv_event_t * e);


// Global variables - accessible from your main code
extern int vreme_rada_motor1;       // Time for motor 1
extern int vreme_rada_motor2;       // Time for motor 2
extern int vreme_pauze;             // Pause time
extern int zeljena_temp_radionice;  // Desired workshop temperature
extern int max_temp_kotla;          // Maximum boiler temperature

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
