// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_ZADAVANJE_TEMPERATURA_H
#define UI_ZADAVANJE_TEMPERATURA_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_zadavanje_temperatura
extern void ui_zadavanje_temperatura_screen_init(void);
extern void ui_zadavanje_temperatura_screen_destroy(void);
extern void ui_event_zadavanje_temperatura(lv_event_t * e);
extern lv_obj_t * ui_zadavanje_temperatura;
extern void ui_event_Button11(lv_event_t * e);
extern lv_obj_t * ui_Button11;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Label26;
extern lv_obj_t * ui_Label27;
extern lv_obj_t * ui_Keyboard1;
extern void ui_event_TextArea1(lv_event_t * e);
extern lv_obj_t * ui_TextArea1;
extern void ui_event_Button12(lv_event_t * e);
extern lv_obj_t * ui_Button12;
extern lv_obj_t * ui_Label28;
extern void ui_event_Button13(lv_event_t * e);
extern lv_obj_t * ui_Button13;
extern lv_obj_t * ui_Label29;
extern lv_obj_t * ui_Label30;
extern lv_obj_t * ui_Label31;
extern lv_obj_t * ui_Container2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

